### ISSUE TITLE
`keyUser` didn't support for nested object result

### ISSUE THREAD

**Issue by lulu8879** [tachibana-shin/vue-auth3#48]
is it possible to make `keyUser` support dot notation like `rolesKey`?
https://vue-auth3.js.org/options/core.html#roleskey
>The key also supports dot notation as in "my.role.key".

example
when trying fetch user data, the respond i have is like this
```
{
    "status": 200,
    "success": true,
    "data": {
        "user": {
            "id": 1,
            "name": "Name",
            "role": "user"
        }
    }
}
```
with current `keyUser` ability, i can't get get user data in `data.user` since it's nested
https://github.com/tachibana-shin/vue-auth3/blob/321a8db1f26cf8fb526f1822223e1a36d916be2a/src/Auth.ts#L567-L572

it would be great is `keyUser` support dot notation like `rolesKey` or custom function like `parseUserData`

**Comment by tachibana-shin** [comment]
I removed this feature because it was facing an XSS attack or syntax issues. I believe it is much more secure to declare on the server for this feature 
for example, if my server (laravel) it usually returns a role field like `["post.read", "post.write", "profile.read"]` if I keep object nesting these roles will never be accessible
